<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-10-20T23:07:44 IST" name="Suite" finished-at="2022-10-20T23:09:01 IST" duration-ms="77194">
    <groups>
    </groups>
    <test started-at="2022-10-20T23:07:44 IST" name="Test" finished-at="2022-10-20T23:09:01 IST" duration-ms="77194">
      <class name="com.assignment.tests.AssignmentTest">
        <test-method is-config="true" signature="BeforeAllMethods()[pri:0, instance:com.assignment.tests.AssignmentTest@6f27a732]" started-at="2022-10-20T23:07:44 IST" name="BeforeAllMethods" finished-at="2022-10-20T23:07:47 IST" duration-ms="2436" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeAllMethods -->
        <test-method signature="testMethod()[pri:0, instance:com.assignment.tests.AssignmentTest@6f27a732]" started-at="2022-10-20T23:07:47 IST" name="testMethod" description="Asignment Test Case" finished-at="2022-10-20T23:09:01 IST" duration-ms="74078" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
The cart total of the added items is not $65.53 expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
The cart total of the added items is not $65.53 expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.assignment.tests.AssignmentTest.testMethod(AssignmentTest.java:184)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod -->
        <test-method is-config="true" signature="getResult(org.testng.ITestResult, java.lang.reflect.Method)[pri:0, instance:com.assignment.tests.AssignmentTest@6f27a732]" started-at="2022-10-20T23:09:01 IST" name="getResult" finished-at="2022-10-20T23:09:01 IST" duration-ms="178" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testMethod status=FAILURE method=AssignmentTest.testMethod()[pri:0, instance:com.assignment.tests.AssignmentTest@6f27a732] output={null}]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void com.assignment.tests.AssignmentTest.testMethod() throws java.lang.InterruptedException,java.io.IOException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method is-config="true" signature="TakeDown()[pri:0, instance:com.assignment.tests.AssignmentTest@6f27a732]" started-at="2022-10-20T23:09:01 IST" name="TakeDown" finished-at="2022-10-20T23:09:01 IST" duration-ms="473" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TakeDown -->
      </class> <!-- com.assignment.tests.AssignmentTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
